# Generated by Django 5.1.2 on 2024-10-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_alter_insumo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
    ]
