# Generated by Django 5.1.2 on 2024-10-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('nombreCompleto', models.CharField(max_length=250)),
                ('domicilioCalle', models.CharField(max_length=200)),
                ('domicilioNumero', models.IntegerField()),
                ('domicilioLocalidad', models.CharField(max_length=200)),
                ('domicilioDepartamento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cantidadDisponible', models.IntegerField()),
                ('unidadMedida', models.CharField(choices=[('UN', 'UNIDAD'), ('GR', 'GRAMOS')], max_length=50)),
                ('tipo', models.CharField(choices=[('PAN', 'PANIFICACION'), ('PAS', 'PASTELERIA')], max_length=200)),
                ('imagen', models.FileField(default='default_image.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCliente', models.CharField(choices=[('MIN', 'MINORISTA'), ('MA', 'MAYORISTA')], max_length=100)),
                ('fechaVenta', models.DateField()),
                ('tipoVenta', models.CharField(max_length=100)),
                ('formaPago', models.CharField(choices=[('EF', 'EFECTIVO'), ('CR', 'CREDITO'), ('DEB', 'DEBITO')], max_length=100)),
                ('tipoComprobante', models.CharField(choices=[('RE', 'RECIBO'), ('FA', 'FACTURA')], max_length=100)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('clienteM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.clientemayorista')),
                ('empleadoVenta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.producto')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
        ),
    ]
