# Generated by Django 5.1.2 on 2024-10-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCliente', models.CharField(max_length=100)),
                ('fechaVenta', models.DateField()),
                ('tipoVenta', models.CharField(max_length=100)),
                ('formaPago', models.CharField(max_length=100)),
                ('tipoComprobante', models.CharField(max_length=100)),
                ('numComprobante', models.IntegerField(unique=True)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('observaciones', models.CharField(max_length=1000)),
            ],
        ),
    ]
