# Generated by Django 5.1.2 on 2024-10-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_usuario'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteMayorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('nombreCompleto', models.CharField(max_length=250)),
                ('domicilioCalle', models.CharField(max_length=200)),
                ('domicilioNumero', models.IntegerField()),
                ('domicilioLocalidad', models.CharField(max_length=200)),
                ('domicilioDepartamento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cantidadDisponible', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=200)),
                ('imagen', models.FileField(default='default_image.jpg', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='empleadoVenta',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='clienteM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.clientemayorista'),
        ),
    ]
