# Generated by Django 5.1.2 on 2024-10-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_clientemayorista_producto_venta_empleadoventa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioProdUnidad', models.DecimalField(decimal_places=2, max_digits=100)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=100)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
        ),
    ]
