# Generated by Django 5.1.2 on 2024-10-23 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='precioProdUnidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='numComprobante',
        ),
        migrations.AlterField(
            model_name='item',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
        ),
    ]
