# Generated by Django 5.1.2 on 2024-10-26 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_usuario'),
        ('venta', '0004_remove_item_precioprodunidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='empleadoVenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
        ),
    ]
