# Generated by Django 5.1.2 on 2024-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_alter_venta_empleadoventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('PAN', 'PANIFICACION'), ('PAS', 'PASTELERIA')], max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidadMedida',
            field=models.CharField(choices=[('UN', 'UNIDAD'), ('GR', 'GRAMOS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='formaPago',
            field=models.CharField(choices=[('EF', 'EFECTIVO'), ('CR', 'CREDITO'), ('DEB', 'DEBITO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipoCliente',
            field=models.CharField(choices=[('MIN', 'MINORISTA'), ('MA', 'MAYORISTA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipoComprobante',
            field=models.CharField(choices=[('RE', 'RECIBO'), ('FA', 'FACTURA')], max_length=100),
        ),
    ]
