# Generated by Django 5.1.2 on 2024-10-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numeroPedido',
        ),
    ]
