# Generated by Django 5.1.2 on 2024-10-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_alter_insumo_nombre'),
        ('pedido', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fechaEmision',
            new_name='fecha_solicitud',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='numeroComprobante',
            new_name='numero_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fechaRecepcion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='montoTotal',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numeroPedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observacionesLlegada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observacionesPeticion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedido.pedido')),
            ],
        ),
    ]
