# Generated by Django 5.1.2 on 2024-11-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_recepcionpedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numero_pedido',
        ),
    ]
