# Generated by Django 5.1.2 on 2024-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(default='default_image.jpg', upload_to=''),
        ),
    ]
